import numpy as np
from datetime import datetime
from typing import Any, Callable, Optional
from .base import BaseAgent, AgentPrediction, AgentHealth, AgentMetadata

class CallableAgentAdapter(BaseAgent):
    """Wraps any Python callable as a standard COGNIX agent."""
    def __init__(self, agent_id: str, func: Callable, name: str = "CallableAgent"):
        self.agent_id = agent_id
        self.func = func
        self.name = name

    def predict(self, inputs: Any) -> AgentPrediction:
        result = self.func(inputs)
        pred = np.array(result)
        return AgentPrediction(
            agent_id=self.agent_id,
            prediction=pred,
            probabilities=np.ones_like(pred, dtype=float),
            confidence=1.0,
            timestamp=datetime.now(),
            raw_output=result
        )

    def estimate_uncertainty(self, inputs: Any) -> float:
        return 0.5  # Default intermediate uncertainty for plain callables

    def metadata(self) -> AgentMetadata:
        return AgentMetadata(self.agent_id, self.name, "general", "callable", "Callable wrapper")

    def health(self) -> AgentHealth:
        return AgentHealth(self.agent_id, True, 1.0, datetime.now())

    def explain(self, inputs: Any) -> str:
        return f"Prediction generated by wrapped callable {self.func.__name__}."


class SklearnAgentAdapter(BaseAgent):
    """Wraps scikit-learn models that implement predict_proba."""
    def __init__(self, agent_id: str, model: Any, name: str = "SklearnAgent"):
        self.agent_id = agent_id
        self.model = model
        self.name = name

    def predict(self, inputs: Any) -> AgentPrediction:
        inputs_arr = np.array(inputs)
        if len(inputs_arr.shape) == 1:
            inputs_arr = inputs_arr.reshape(1, -1)
            
        pred = self.model.predict(inputs_arr)
        if hasattr(self.model, "predict_proba"):
            probs = self.model.predict_proba(inputs_arr)
            conf = float(np.max(probs, axis=1)[0]) if len(probs) > 0 else 1.0
        else:
            probs = np.ones_like(pred, dtype=float)
            conf = 1.0
            
        return AgentPrediction(
            agent_id=self.agent_id,
            prediction=pred,
            probabilities=probs,
            confidence=conf,
            timestamp=datetime.now(),
            raw_output=pred
        )

    def estimate_uncertainty(self, inputs: Any) -> float:
        # Simple entropy-based uncertainty approximation
        inputs_arr = np.array(inputs)
        if len(inputs_arr.shape) == 1:
            inputs_arr = inputs_arr.reshape(1, -1)
            
        if hasattr(self.model, "predict_proba"):
            probs = self.model.predict_proba(inputs_arr)[0]
            # Normalized entropy
            entropy = -np.sum(probs * np.log(probs + 1e-9)) / np.log(len(probs) + 1e-9)
            return float(np.clip(entropy, 0.0, 1.0))
        return 0.5

    def metadata(self) -> AgentMetadata:
        return AgentMetadata(self.agent_id, self.name, "ml", "tabular", "Sklearn wrapper")

    def health(self) -> AgentHealth:
        return AgentHealth(self.agent_id, True, 1.0, datetime.now())

    def explain(self, inputs: Any) -> str:
        return f"Prediction generated by sklearn model {type(self.model).__name__}."


class PyTorchAgentAdapter(BaseAgent):
    """Wraps PyTorch nn.Module models."""
    def __init__(self, agent_id: str, model: Any, name: str = "PyTorchAgent"):
        self.agent_id = agent_id
        self.model = model
        self.name = name
        # Optional PyTorch import
        import torch
        self.torch = torch

    def predict(self, inputs: Any) -> AgentPrediction:
        self.model.eval()
        with self.torch.no_grad():
            outputs = self.model(inputs)
            if isinstance(outputs, self.torch.Tensor):
                probs = self.torch.softmax(outputs, dim=-1).cpu().numpy()
                pred = np.argmax(probs, axis=-1)
                conf = float(np.max(probs, axis=-1)[0]) if len(probs) > 0 else 1.0
            else:
                probs = np.array([1.0])
                pred = np.array(outputs)
                conf = 1.0
                
        return AgentPrediction(
            agent_id=self.agent_id,
            prediction=pred,
            probabilities=probs,
            confidence=conf,
            timestamp=datetime.now(),
            raw_output=outputs
        )

    def estimate_uncertainty(self, inputs: Any) -> float:
        # Very simple baseline uncertainty for PyTorch models unless MC Dropout is used
        pred = self.predict(inputs)
        return 1.0 - pred.confidence

    def metadata(self) -> AgentMetadata:
        return AgentMetadata(self.agent_id, self.name, "deep_learning", "tensor", "PyTorch wrapper")

    def health(self) -> AgentHealth:
        return AgentHealth(self.agent_id, True, 1.0, datetime.now())

    def explain(self, inputs: Any) -> str:
        return f"Prediction generated by PyTorch model {type(self.model).__name__}."


class LLMAgentAdapter(BaseAgent):
    """Wraps an LLM callable that returns text and optional confidence."""
    def __init__(self, agent_id: str, llm_callable: Callable, name: str = "LLMAgent"):
        self.agent_id = agent_id
        self.llm_callable = llm_callable
        self.name = name

    def predict(self, inputs: Any) -> AgentPrediction:
        # Expects llm_callable to return a dict with 'text' and optionally 'confidence'
        result = self.llm_callable(inputs)
        if isinstance(result, dict):
            text = result.get('text', str(result))
            conf = result.get('confidence', 0.8)
        else:
            text = str(result)
            conf = 0.8
            
        return AgentPrediction(
            agent_id=self.agent_id,
            prediction=np.array([text]),
            probabilities=np.array([conf]),
            confidence=float(conf),
            timestamp=datetime.now(),
            raw_output=result
        )

    def estimate_uncertainty(self, inputs: Any) -> float:
        pred = self.predict(inputs)
        return 1.0 - pred.confidence

    def metadata(self) -> AgentMetadata:
        return AgentMetadata(self.agent_id, self.name, "nlp", "text", "LLM Wrapper")

    def health(self) -> AgentHealth:
        return AgentHealth(self.agent_id, True, 1.0, datetime.now())

    def explain(self, inputs: Any) -> str:
        return "Prediction generated by language model."
