"""
Runtime Data Provenance.

Structures to track the origin of every metric and decision generated by the framework.
Revision 3: Added ModuleStatus for per-module execution traceability.
"""
from dataclasses import dataclass, field, asdict
from typing import Any, Optional
import time


@dataclass
class ModuleStatus:
    """
    Per-module execution status record.
    Populated by CognixPipeline for every decision cycle.
    If executed=False in research mode, the run is marked INVALID.
    """
    executed: bool
    method: str                         # e.g. "mc_dropout", "epistemic_gat"
    duration_ms: float
    failure_reason: Optional[str]       # None if executed successfully
    inputs_validated: bool = False
    outputs_validated: bool = False

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class MetricProvenance:
    """Traceability for an individual metric."""
    metric_name: str
    value: Any
    unit: str
    formula: str
    source_module: str
    source_function: str
    input_ids: list[str]
    dataset: str
    model: str
    experiment: str
    run_id: str
    seed: int
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class DecisionTrace:
    """Complete traceable log for a single decision cycle."""
    timestamp: float
    input_id: str
    agent_predictions: dict[str, Any]
    uncertainty: dict[str, Any]
    belief: list[float]
    weights: dict[str, float]
    communication: dict[str, Any]
    calibration: dict[str, Any]
    risk: str
    decision: str
    attribution: dict[str, float]
    latency: dict[str, float]
    module_status: dict[str, Any] = field(default_factory=dict)
    metrics: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class ExperimentMetadata:
    """Metadata for an entire experiment run."""
    run_id: str
    dataset: str
    dataset_version: str
    model: str
    model_version: str
    experiment: str
    seed: int
    timestamp: float = field(default_factory=time.time)
    git_commit: str = "UNKNOWN"
    configuration: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return asdict(self)
